language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp bower tsd@next typescript karma-cli
- npm install
- bower install
- tsd reinstall
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- gulp testForCI
after_script:
- gulp coveralls
notifications:
  hipchat:
    rooms:
      secure: kzIdD8lcPJsJLpx5vZpU2GTJn7B7Gs1aSjZFqfaPrgxU4bUPkUhTlTq7pp/oUtqrG/DyaMEH0JUjroItRu/PphsVN0dwUmCWwA1J6ARU0oAIkT3Ifhm31Q9YuZC7N8dck79VZXy0tWqAcZIBIKOFPiCGJ5uKR3qHWIhq1Rmw1C0=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html